spring:
  redis:
    host: 192.168.2.101
    port: 6379
    password: 123456
    database: 2
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

#spring.red=localhost
#spring.redis.port=6379
#  # Redis服务器连接密码（默认为空）
#spring.redis.password=*****
#  #默认是数据库0
#spring.redis.database= 0
#
#  # 连接池最大连接数（使用负值表示没有限制） 默认 8
#spring.redis.lettuce.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#spring.redis.lettuce.pool.max-wait=-1
#  # 连接池中的最大空闲连接 默认 8
#spring.redis.lettuce.pool.max-idle=8
#  # 连接池中的最小空闲连接 默认 0
#spring.redis.lettuce.pool.min-idle=0